language: java
jdk:
  - oraclejdk8

install: true

script: mvn clean install

# after_success:
#  - branches:
#    - only:
#      - dev
#    - notifications:
#      - email:
#        - contact@avionicengineers.com

notifications:
  email:
    recipients:
      - contact@avionicengineers.com
    on_success: always
    on_failure: always